/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;


        public class Library {
            public boolean someLibraryMethod() {
                return true;
            }
            public static void main(String[] args) {
                BinaryTree<String> newTree = new BinaryTree<>();

                Node<String> nodeD = new Node<>("D");
                Node<String> nodeE = new Node<>("E");
                Node<String> nodeB = new Node<>("B", nodeD, nodeE);
                Node<String> nodeF = new Node<>("F");
                Node<String> nodeC= new Node<>("C", nodeF, null);
                Node<String> newTreeRoot = new Node<>("A", nodeB, nodeC);
                System.out.println(newTree.preOrder(newTreeRoot));
                System.out.println(newTree.inOrder(newTreeRoot));
                System.out.println(newTree.postOrder(newTreeRoot));
                System.out.println(newTree.toString());

            }
}
