/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

public class Library {
    public static void main(String[] args) {
        Stack<Integer> stack = new Stack<Integer>();
        System.out.println(stack.pop());
        System.out.println(stack.peek());
        stack.push(5);
        stack.push(4);
        System.out.println(stack);
        System.out.println(stack.pop());
        System.out.println(stack.peek());
        System.out.println(stack);
        System.out.println(stack.isEmpty());

        Queue<Integer> queue = new Queue<>();
        queue.enqueue(5);
        queue.enqueue(4);
        queue.enqueue(3);
        System.out.println(queue);
        queue.dequeue();
        System.out.println("after dequeue"+queue);
        queue.peek();
        System.out.println(queue.peek());
        System.out.println("lab11");
        Stack<Integer> ontherStack = new Stack<Integer>();
        ontherStack.push(1);
        ontherStack.push(2);
        ontherStack.push(3);
        ontherStack.push(4);
        ontherStack.pop();
        System.out.println(ontherStack);
    }






}

