/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList2;

public class Library {
    public static void main(String[] args) {


        LinkedList linksList = new LinkedList();
        System.out.println(linksList.toString());
        linksList.insert("c");
        linksList.insert("b");
        linksList.insert("a");

        System.out.println(linksList.toString());
//        System.out.println(linksList.kthFromEnd(0));


        LinkedList linksList1 = new LinkedList();
        linksList1.insert("c");
        linksList1.insert("b");
        linksList1.insert("a");
        System.out.println(linksList1);
        System.out.println(linksList.ziplists(linksList1, linksList));

    }
}

